apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: qdrant-upsert-action
  annotations:
    camel.apache.org/kamelet.support.level: "Experimental"
    camel.apache.org/catalog.version: "0.0.1"
    camel.apache.org/provider: "rRed Hat"
    camel.apache.org/kamelet.group: "ai"
    camel.apache.org/kamelet.namespace: "Sink"
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "Qdrant Upsert Sink"
    description: ""Qdrant Upsert Sink"
    type: object
    properties:
      collectionName:
        title: 'Collection Name'
        description: 'Collection Name'
        type: string
      qdrantHost:
        title: 'Qdrant Host'
        description: 'Qdrant Host'
        type: string
      qdrantPort:
        title: 'Qdrant Port'
        description: 'Qdrant Port'
        type: integer
        default: 6334
  dependencies:
    - "camel:kamelet"
    - "camel:core"
    - "camel:qdrant"
  template:
    from:
      uri: 'kamelet:source'
      steps:
        - setHeader:
            name: 'CamelQdrantAction'
            constant: 'UPSERT'
        - to:
            uri: "qdrant:{{collection}}"
            parameters:
              host: "{{qdrantHost}}"
              port: "{{qdrantPort}}"