apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: qdrant-create-action
  annotations:
    camel.apache.org/kamelet.support.level: "Experimental"
    camel.apache.org/catalog.version: "0.0.1"
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.group: "ai"
    camel.apache.org/kamelet.namespace: "Transformation"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  dependencies:
    - "camel:kamelet"
    - "camel:core"
    - "camel:timer"
  template:
    from:
      uri: 'timer:start?repeatCount=1'
      steps:
        - process:
            ref: "createCollectionProcessorBean"